### ISSUE TITLE
`IndexError` when running `from renardo_lib import *` in VS Code

### ISSUE THREAD

**Issue by jsquaredosquared** [e-lie/renardo#23]
Here is the error:

```python
>>> from renardo_lib import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_lib/__init__.py", line 10, in <module>
    from renardo_lib.TempoClock import *
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_lib/TempoClock.py", line 58, in <module>
    from renardo_lib.Players import Player
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_lib/Players.py", line 130, in <module>
    from renardo_lib.Buffers import Samples
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_lib/Buffers.py", line 408, in <module>
    Samples = BufferManager()
              ^^^^^^^^^^^^^^^
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_lib/Buffers.py", line 132, in __init__
    self._paths = [spack_manager.default_spack().loop_path] + list(paths)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_gatherer/samples_download.py", line 116, in default_spack
    return self.get_spack(0)
           ^^^^^^^^^^^^^^^^^
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/renardo_gatherer/samples_download.py", line 130, in get_spack
    self._samples_packs.values()[num_or_spack]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/jj/Desktop/try_live_coding/.venv/lib/python3.12/site-packages/indexed/__init__.py", line 186, in __getitem__
    key = self._mapping._map[index]
          ~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

Is there any way to fix this? Could you check if the collection be empty?

**Comment by jsquaredosquared** [comment]
Whoops, I forgot to initialize Renardo. My bad.
